### ISSUE TITLE
Use better notification texts

### ISSUE THREAD

**Issue by oskarnrk** [smartcommunitylab/smartcampus.vas.rifiuti.android#17]

**Comment by zaccog** [comment]
Proposta da verificare:
- Versione breve per 1 notifica: titolo: Domani a "località" - testi: "tipo di raccolta" 
- Versione breve per <n> notifiche: titolo: Domani a "località" - testi: Porta a porta "elenco"
- Versione lunga: [da 1 a <n> righe] titolo: Domani a "località" - testi: "tipo di raccolta" 

Per i CRM non mettiamo nulla giusto?
