### ISSUE TITLE
"Add note" dialog has bad UI

### ISSUE THREAD

**Issue by oskarnrk** [smartcommunitylab/smartcampus.vas.rifiuti.android#34]
The button has the standard Android gray layout. Maybe we can use AlertDialog...?

**Comment by zaccog** [comment]
I agree. How do we proceed. @paolaR  or you, @oskarnrk, do it directly?

**Comment by oskarnrk** [comment]
I'll talk to @paolaR but I think I can change it by myself, design is not required.
