### ISSUE TITLE
cannot delete profiles

### ISSUE THREAD

**Issue by zaccog** [smartcommunitylab/smartcampus.vas.rifiuti.android#44]
The icon for deleting a profile seems to have disappeared

**Comment by oskarnrk** [comment]
It's not possible delete a profile in use, but it's implicit.
So we can always show the trash icon in the actionbar but when clicked, if the profile is in use, an alert tells the user that it's not possible delete it.

**Comment by zaccog** [comment]
ok

**Comment by oskarnrk** [comment]
The world must know: the solution was provided by @zaccog!
Fixed
