### ISSUE TITLE
Show "Contact" on map

### ISSUE THREAD

**Issue by zaccog** [smartcommunitylab/smartcampus.vas.rifiuti.android#52]
For the 3 items in the Contacts list ((Servizio TIA e informatica, Ufficio Igiene Ambientale, SOGAP SRL), the "show on map" feature should not launch a "direction" intent. It should rather directly show a map and the marker for that contact.

**Comment by oskarnrk** [comment]
Remove "directions" action from actionbar, put this functionality and change icon of "location" in the list. Waiting for green arrow icon. EDIT: already received!
